name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          # --- Crear el Reporte ---
          # Sobrescribe report.md con las métricas (usa > en lugar de >> la primera vez)
          echo "## Resultados del Modelo" > report.md
          cat metrics.txt >> report.md
          
          # Añadir las 3 imágenes generadas al reporte
          echo "### Historial de Entrenamiento" >> report.md
          echo "![](./training_history.png)" >> report.md
          
          echo "### Matriz de Confusión" >> report.md
          echo "![](./confusion_matrix.png)" >> report.md
          
          echo "### Reporte de Clasificación" >> report.md
          echo "![](./classification_report_heatmap.png)" >> report.md
          
          # Publicar el reporte como un comentario
          cml comment create report.md
          
          # cat metrics.txt >> report.md
          # echo "![](./plot.png)" >> report.md
          # cml comment create report.md

          # cat metrics.txt >> README.md
          # echo "![](./plot.png)" >> README.md
          # cml comment create README.md
